# Generated by Django 3.0.3 on 2020-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0002_kuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
    ]
