# Generated by Django 3.0.3 on 2020-02-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0003_auto_20200227_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuser',
            name='nickname',
            field=models.CharField(default='nick', max_length=32, verbose_name='Nickname'),
            preserve_default=False,
        ),
    ]
