# Generated by Django 3.0.3 on 2020-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0005_auto_20200228_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuser',
            name='level',
            field=models.CharField(choices=[('3', 'admin'), ('2', 'seller'), ('1', 'user')], max_length=8, verbose_name='등급'),
        ),
    ]
