# Generated by Django 3.0.3 on 2020-02-27 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200227_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='registered_dttm',
        ),
        migrations.AddField(
            model_name='board',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록날짜'),
            preserve_default=False,
        ),
    ]
