# Generated by Django 3.0.3 on 2020-02-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200227_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='registered_date',
            new_name='register_date',
        ),
    ]
